#!/usr/bin/bash
cd /home/al/localhost/www/glass/base
sudo mount.cifs -o username=guest,password="" //sun/onko2003/data onko2003/

echo "start"

cp onko2003/ACATALOG.DBF ACATALOG.DBF
cp onko2003/person.dbf person.dbf
cp onko2003/zank.dbf zank.dbf
cp onko2003/ZFCAC.DBF ZFCAC.DBF
cp onko2003/ZPOST.DBF ZPOST.DBF
cp onko2003/ZPOSTCH.DBF ZPOSTCH.DBF
cp onko2003/zsubdiv.dbf zsubdiv.dbf
cp onko2003/zTipDol.DBF zTipDol.DBF

#rm *.xls
#rm *.csv

#soffice --convert-to xls *.*

#soffice --convert-to csv *.xls

#rm *.xls
# нужно убирать кривой столбец из таблицы ACATALOG
# Очистить его полностью, вместе с заголовком, но не удалять как столбец, иначе не будет связи между отделениями

echo "end"

exit

sudo umount onko2003



